### ISSUE TITLE
Incomplete output from the pipeline (upto BLINKER)

### ISSUE THREAD

**Issue by sanjibksaha** [tarsqi/ttk#26]
[wsj_0169.txt](https://github.com/tarsqi/ttk/files/328824/wsj_0169.txt)

The processing did not complete and generated an incomplete output file.
[WSJ_0169.TXT](https://github.com/tarsqi/ttk/files/328832/WSJ_0169.TXT)

The latest TTK pipeline (upto BLINKER module, Python version) has been run on this file.
Here is the console output:

> C:\Users\sahask\workspace\TTK-2-UIMA-Fit\Tarsqi\resources\ttk\code>python tarsqi
> .py --source=timebank --pipeline=PREPROCESSOR,GUTIME,EVITA,SLINKET,S2T,BLINKER P
> :\workspace\ValidationData\TimeBank_dataset\TimeBank_unannotated\wsj_0169.xml C:
> \Users\sahask\workspace\TTK-2-UIMA-Fit\Resources\out\test1.out
>         reading parameters ...
>         tagging ...
> ERROR printing output
>          finished.

We also tried to run the entire pipeline, provides the same result.

**Comment by marcverhagen** [comment]
Fixed in https://github.com/tarsqi/ttk/commit/bab615ca2b5f41317d90cb1cf9e0894eb6886ce8.

However, this issue does bring up the fact that the behavior of Evita when there are already event tags in the input is not well-defined (see issue https://github.com/tarsqi/ttk/issues/3). This is probably true for other components too.

**Comment by sanjibksaha** [comment]
[wsj_0169.txt](https://github.com/tarsqi/ttk/files/330239/wsj_0169.txt)

I tried with this Timebank file and got the same problem. I uploaded the wrong file in my previous comment.

**Comment by marcverhagen** [comment]
I can run the code on wsj_0169.txt just fine.
